debug: true

springdoc:
    show-actuator: true

server:
  servlet:
    context-path: /
  port: 8088
  
logging:
   level:
     root: debug
     org.springframework: debug
     org.hibernate: debug
     org.springframework.transaction.interceptor: info
     org.springframework.data: debug
     org.springframework.data.rest: debug
     org.springframework.data.jpa.repository: debug
     org.springframework.data.jpa.repository.support: debug
  
  
spring:
  jmx:
    enabled: true
  boot:
    admin:
      client:
        enable: true
        auto-registration: true
  activemq:
   broker-url: tcp://localhost:61616
  datasource:
    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/simplefkdb
    url: jdbc:postgresql://127.0.0.1:5432/simplefkdb
    username: postgres 
    password: postgres123   
  hikari:
    connectionTimeout: 30000
    maximumPoolSize: 250
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.globally_quoted_identifiers: true
    hibernate.current_session_context_class: thread
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        current_session_context_class: thread
        ddl-auto: create-drop
        javax:
         cache:
            provider: org.ehcache.jsr107.EhcacheCachingProvider
        cache:
           use_second_level_cache: false
           use_query_cache: false
           region:
              factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  ehcache:
      config: classpath:ehcache.xml                  
  properties:
    javax:
      persistence:
        sharedCache: 
            #required - enable selective caching mode - only entities with @Cacheable annotation will use L2 cache.
        mode: ENABLE_SELECTIVE 
  cloud:
     config:
       enabled: false
  graphql:
    schema:
      printer:
        enabled: true            
     
management:
   endpoint:
     health:
       show-details: always
   endpoints:
      web:
         cors:
           allowed-origins: '*'
           allowed-methods: GET,POST
         base-path: /actuator
         exposure:
            include: "*"
   jmx:
     exposure:
       include: "*"
       